INSERT INTO IRRIGATION (ID, MINUTES_PER_ACRE, WATER_PER_ACRE) VALUES (1, 20, 2000);
INSERT INTO IRRIGATION (ID, MINUTES_PER_ACRE, WATER_PER_ACRE) VALUES (2, 30, 3000);
INSERT INTO IRRIGATION (ID, MINUTES_PER_ACRE, WATER_PER_ACRE) VALUES (3, 40, 4000);
INSERT INTO IRRIGATION (ID, MINUTES_PER_ACRE, WATER_PER_ACRE) VALUES (4, 50, 5000);
INSERT INTO IRRIGATION (ID, MINUTES_PER_ACRE, WATER_PER_ACRE) VALUES (5, 60, 6000);


INSERT INTO PLOT (ID, AREA_IN_ACRE, TIME_SLOT, IRRIGATION_ID) VALUES (1, 2, '02:10:10', 1);
INSERT INTO PLOT (ID, AREA_IN_ACRE, TIME_SLOT, IRRIGATION_ID) VALUES (2, 3, '03:20:20', 2);
INSERT INTO PLOT (ID, AREA_IN_ACRE, TIME_SLOT, IRRIGATION_ID) VALUES (3, 4, '04:30:20', 3);
INSERT INTO PLOT (ID, AREA_IN_ACRE, TIME_SLOT, IRRIGATION_ID) VALUES (4, 5, '05:40:20', 4);
INSERT INTO PLOT (ID, AREA_IN_ACRE, TIME_SLOT, IRRIGATION_ID) VALUES (5, 6, '06:50:20', 5);